### ISSUE TITLE
DeprecationWarning

### ISSUE THREAD

**Issue by hyuce** [carlos8f/zenbot#1725]
### System information
- **Have I written custom code (as opposed to using zenbot vanilla)**:No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Mint 19 (Ubuntu bionic based)
- **Zenbot version** (commit ref, or version):  4.1.4 / Commits on Oct 1, 2018 
- **Zenbot branch**: unstable
- **NodeJS version**: 8.12.0
- **Python version (when using a python script)**: 3.6.6
- **Exact command to reproduce (include everything)**:
- **Did I make any changes to conf-sample.js?**: No

### Describe the problem
When I execute the below code
```console 
foo@bar:~$ ./zenbot.sh sim binance.INS-ETH --strategy=trend_bollinger --days 14  --period_length=30m
```
zenbot says blow output but The program continues.

### Source code / Error logs
```console 
(node:6158) DeprecationWarning: collection.save is deprecated. Use insertOne, insertMany, updateOne, or updateMany instead.
(node:6431) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
(node:6431) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
```

**Comment by hyuce** [comment]
#1715

**Comment by DeviaVir** [comment]
https://github.com/DeviaVir/zenbot/issues/1715

**Comment by AlekFranco** [comment]
add this to your env (viz: using .bashrc in unix)

NODE_NO_WARNINGS=1
NODE_PENDING_DEPRECATION=0

save .bashrc then reboot or export it via 

 .  ~/.bashrc

Also, start your  mongod with the --quiet parameter.

Your zenbotting should be peaceful from here on
