### ISSUE TITLE
use_fee_asset setting

### ISSUE THREAD

**Issue by hyuce** [carlos8f/zenbot#1728]
### System information
- **Have I written custom code (as opposed to using zenbot vanilla)**:No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Mint 19 (Ubuntu bionic based)
- **Zenbot version** (commit ref, or version):  4.1.4 / Commits on Oct 1, 2018 
- **Zenbot branch**: unstable
- **NodeJS version**: 8.12.0
- **Python version (when using a python script)**: 3.6.6
- **Exact command to reproduce (include everything)**:
- **Did I make any changes to conf-sample.js?**: No

### Describe the problem
When I execute the below code
```console 
foo@bar:~$ ./gen.binance.xxx-usdt.sh --conf=conf-binance.XXX-USDT.js --use_fee_asset  --debug 
```
Live trade shows current in trade options as follows. Also the option has conf file like `c.use_fee_asset = true` .

### Source code / Error logs
```console 
use_fee_asset: false,
```
Why doesn't it handle this parameter?
What should I do?

**Comment by hyuce** [comment]
I tried everything but I couldn't succeed. a tip is enough.

**Comment by hyuce** [comment]
My problem is still continuing. Does anyone use this setting?

**Comment by BAKFR** [comment]
I've looked into the code: seems like `use_fee_asset` don't change anything to live orders.
The only change is in the computation of estimated fees (displayed on debug, and used to detect orders too small).

Anyway, if you want to pay the fees using the exchange's currency, you should look into the exchange settings.

**Comment by hyuce** [comment]
I use BNB for Fee at Binance. Can't I use  `use_fee_asset` for this fee?

**Comment by BAKFR** [comment]
I'm not 100% sure, but I think Zenbot will use BNB if you have enabled BNB fees on Binance.

The Binance API doesn't have any way to specify this setting.

**Comment by hyuce** [comment]
You are absolutely right.  Zenbot use BNB if I have enabled BNB fees on Binance. There's a situation like this #1735 . It's making the calculation wrong.
