### ISSUE TITLE
Zenbot order look different from Binance

### ISSUE THREAD

**Issue by hyuce** [carlos8f/zenbot#1735]
### System information
- **Have I written custom code (as opposed to using zenbot vanilla)**:No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Mint 19 (Ubuntu bionic based)
- **Zenbot version** (commit ref, or version):  4.1.4 / Commits on Oct 1, 2018 
- **Zenbot branch**: unstable
- **NodeJS version**: 8.12.0
- **Python version (when using a python script)**: 3.6.6
- **Exact command to reproduce (include everything)**:
- **Did I make any changes to conf-sample.js?**: No

### Describe the problem
I set up the system, simulated it and based on this result, I have been live trading for a week. But the Zenbot order look different from Binance, let's give an example; Zenbot give 198 XLM / BTC sales order. But in Binance, 188 XLM / BTC is shown (operation has ordered). 
Similar situation buying is also valid. for example; Zenbot 529 XLM / BTC has made a buy order. But in Binance, 511 XLM / BTC is shown (operation has bought). - I'm using --use_fee_asset parameter. The commission in the order was taken as BNB.

Anybody have any ideas?

**Comment by sahni619** [comment]
yes it happens to me as well. Trade executes successfully on the CLI but the information on the exchange and CLI differs.
