### ISSUE TITLE
linux need this?

### ISSUE THREAD

**Issue by fachos** [carlos8f/zenbot#1739]
it only an optional installation.. can i ignore this?
or how to fix? thank you..

npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: arm64

**Comment by DeviaVir** [comment]
Please use the issue template when opening your ticket.
