### ISSUE TITLE
gdax.ZRX-BTC not working -  size is too accurate. Smallest unit is 0.00001000

### ISSUE THREAD

**Issue by mroxso** [carlos8f/zenbot#1776]
### System information
- **Have I written custom code (as opposed to using zenbot vanilla)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux/Debian 9
- **Zenbot version** (commit ref, or version): latest
- **Zenbot branch**: unstable
- **NodeJS version**: v10.13.0
- **Python version (when using a python script)**: n/a
- **Exact command to reproduce (include everything)**: zenbot trade --conf my_conf.js
- **Did I make any changes to conf-sample.js?**: I just copied to my_conf.js and replaced GDAX API keys

When my zenbot trys to buy something on GDAX:

`data:
   { message: 'size is too accurate. Smallest unit is 0.00001000' } }
[ { price: '0.00009479',
    size: '87.65693322',
    fee: null,
    orig_size: '87.65693322',
    remaining_size: '87.65693322',
    orig_price: '0.00009479',
    cancel_after: 'day',
    product_id: 'ZRX-BTC',
    post_only: true,
    time_in_force: 'GTT',
    side: 'buy' } ]`

It seems like it's a problem with selector gdax.ZRX-BTC

**Comment by rountrey** [comment]
Any news on this? It also happens on gdax.BAT.USDC

Edit: it seems that the 8 decimal places might be the cause. Is there a way to cut it off to 5 or 6?

**Comment by rountrey** [comment]
Did some investigating, it seems that gdax.BAT-USDC (all USDC, really) and gdax.ZRX-BTC are placed in limit order mode on CoinbasePro. This may be the cause of the issues.

https://status.pro.coinbase.com/incidents/hyfyg5zsqk1w

**Comment by mmdiego** [comment]
It happened the same to me using XLM-USD. The problem is that all products in gdax are defined to use a precision of 8 decimal places in zenbot, but that is not compatible with the exchange.
The fix is very simple and consists of defining the parameter "asset_increment" in the products' definitions, as was done for Binance exchange in #1380 .

**Comment by mmdiego** [comment]
I've implemented the fix locally and it worked. I'll try to upload the fix but I'll have to learn Git =S
