### ISSUE TITLE
Zenbot simulation breaks on mongodb error

### ISSUE THREAD

**Issue by mrseeker** [carlos8f/zenbot#1787]
### System information
- **Have I written custom code (as opposed to using zenbot vanilla)**: Yes, but have not rewritten engine.
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Debian 9
- **Zenbot version** (commit ref, or version): g7b9aec9
- **Zenbot branch**: 4.0.1
- **NodeJS version**: 10.6
- **Python version (when using a python script)**: n/a
- **Exact command to reproduce (include everything)**: ./zenbot.sh sim --days=30
- **Did I make any changes to conf-sample.js?**: No

### Describe the problem
When running zenbot in simulation, it tends to stop without any reason. Logging in mongodb shows errors related to the connection, which causes it to drop the connection. Preferred method would be showing a connection error with the database and trying to reconnect.

### Source code / Error logs
MongoDB Error:
2018-12-03T11:54:48.823+0100 I NETWORK  [conn998] SocketException handling request, closing client connection: 9001 socket exception [SEND_ERROR] server [127.0.0.1:35570]
2018-12-03T11:54:49.272+0100 I NETWORK  [conn999] end connection 127.0.0.1:35574 (12 connections now open)

Reproducable only when the mongoDB drops the connection (either due to restart, network connection issues, etc.) during a long simulated run of zenbot. Run zenbot in a long simulation and kill the connection.

**Comment by hyuce** [comment]
Make sure your mongodb service is running. If it is working, please review its mongodb permissions.

**Comment by mrseeker** [comment]
"make sure your mongodb service is running" -> Yes it is.
"Review its mongodb permission" -> What permissions do I need to check?

Just for your information, I can run simulations. The problem is that when mongodb drops the connection (due to an unknown error), the simulation fails midway... And when you are crunching 6 months of data, its pretty annoying to see a dropped connection being the cause of the whole simulation failing.

**Comment by hyuce** [comment]
check [here](https://docs.mongodb.com/manual/tutorial/manage-users-and-roles/) 
> "make sure your mongodb service is running" -> Yes it is.
> "Review its mongodb permission" -> What permissions do I need to check?
> 
> Just for your information, I can run simulations. The problem is that when mongodb drops the connection (due to an unknown error), the simulation fails midway... And when you are crunching 6 months of data, its pretty annoying to see a dropped connection being the cause of the whole simulation failing.

**Comment by mrseeker** [comment]
@hyuce Just to give you some background information:
I am running mongoDB locally, I don't have any permissions set. I can run backfill, simulations and use the bot for trading. This is not an issue. The issue is as follows:

What I see:
- Bot connects to mongoDB.
- Bot runs simulation
- Bot requests more data, mongoDB returns data.
(this is the most important part)
- An unknown condition (most likely race condition) occurs in the database, mongoDB returns a fatal alert and drops the connection.
- Bot silently terminates.

My expectation:
- Bot connects to mongoDB
- Bot runs simulation
- Bot requests more data, mongoDB returns data
- An unknown condition (most likely race condition) occurs in the database, mongoDB returns a fatal alert and drops the connection.
- Bot reconnects to mongoDB
- Bot runs simulation
[...]
