### ISSUE TITLE
forex.analytics crashes 'char const*'

### ISSUE THREAD

**Issue by EAS-Innovations** [carlos8f/zenbot#1802]
### System information
- **Have I written custom code (as opposed to using zenbot vanilla)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04.1 server
- **Zenbot version** (commit ref, or version): 4.1.0
- **Zenbot branch**: ?
- **NodeJS version**: 8.14.1
- **Python version (when using a python script)**:
- **Exact command to reproduce (include everything)**: ./zenbot trade binance.etc-btc --strategy forex_analytics --modelfile eth-btc.json
- **Did I make any changes to conf-sample.js?**: binance api key and telegram bot Settings

### Describe the problem
I've train with command "./zenbot Train binance.etc-btc --days_training 42 --days_test 14". After that I renamed the json file and run with the command above. After download complete, zenbot starts and crashs imidiatly with following error: "terminate called after throwing an instance of 'char const*' Aborted (core dumped)"

What's the problem?
Where can I find additional error logs/dumps?

**Comment by colinbouvry** [comment]
### System information
* **Have I written custom code (as opposed to using zenbot vanilla)**: No
* **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04.5 LTS server
* **Zenbot version** (commit ref, or version): 4.1.0
* **Zenbot branch**: unstable 13/02/2019
* **NodeJS version**: 8.15.0
* **Python version (when using a python script)**: 2.7
* **Exact command to reproduce (include everything)**: sh zenbot.sh trade gdax.LTC-EUR --deposit 100 --strategy forex_analytics --modelfile models/forex.model_gdax.LTCEUR_...json --period=1m --paper --conf conf3.js

### Describe the problem
The same problem :
crashs imidiatly with following error: "terminate called after throwing an instance of 'char const*

```
sh zenbot.sh train gdax.LTC-EUR --period 1m --days_training 20 --days_test 5

sh zenbot.sh trade gdax.LTC-EUR --deposit 100 --strategy forex_analytics --modelfile models/forex.model_gdax.LTCEUR_...json --period=1m --paper --conf conf3.js
```

Any idea ?
