### ISSUE TITLE
bugs with price

### ISSUE THREAD

**Issue by Zergyc** [carlos8f/zenbot#1848]
there is issue with zenbot trades in binance
all strats doing same thing 

SELL | 395.83682999 TRX | 0.0751463 XRP | 29.7456613 XRP | 0.02974566  XRP | 0.0000% | 2019-03-26 09:19:56 | a few seconds 
BUY | 421.14715368 TRX | 0.0720593 XRP | 30.3475859 XRP | 0.42114715  TRX | 0.0000% | 2019-03-26 09:10:56 | a few seconds |

in binance it shows up with diferent price

03-26 11:19:50 | TRX/XRP | Market | Sell | 0.07450000 | market | 395.8 | 395.8 | 29.48710 XRP | -- 
03-26 11:10:50 | TRX/XRP | Market | Buy | 0.07463000 | market | 421.1 | 421.1 | 31.42670 XRP | 

System info ubuntu 18.04 server
latest zenbot unstable build
./conf.js default

**Comment by GmasteR** [comment]
I have the same
