### ISSUE TITLE
Duplicated trade leading to wrong volume data

### ISSUE THREAD

**Issue by BAKFR** [carlos8f/zenbot#1851]
When the backfill Zenbot is executed several times in a row, some trades are duplicated.

In some cases, trades are fetched from exchange when they already exists in database. The direct effect is that OHLCV periods computed from this have incorrect volume data.

**Volume data from "pre-roll" period can't be trusted.**
**It affects both the trade command and the sim command**

## How to reproduce

At 10h00, start a `zenbot trade`
At 10h05, stop it.
At 10h10, start it again.

Volume values from 10h00 to 10h05 are twice as much the real values.

## Code details

There is a mechanism in backfill.js that is supposed to handle this case: It uses some *marker* objects, (stored in the `resume_markers` mongo table) to register timespan of registered trades. Unfortunately, it doesn't works.
There is a lot of case to handle (backfill over a timespan with zero, one or several *markers*. the *markers* can be fully included in the selected timespan, or only partially).

The current code don't handle any of this and is poorly designed.

----
I will not fix this myself: I have a workaround for my custom code and so I'm not impacted by this.
This issue is here to let people know, and give some hints for the ones willing to address the problem.

**Comment by jorisw** [comment]
This is supposed to be handled by unique IDs on trades in the format of `binance.ETH-USDT-9438710239`, which `trade.js` forgets to assign. Fixed in #2517.
