### ISSUE TITLE
Cannot find module '/app/extensions/exchanges/sim/exchange'

### ISSUE THREAD

**Issue by DooDiddle** [carlos8f/zenbot#1882]
I am using Windows with Docker containers. I am puzzled by this error on startup: 
Cannot find module '/app/extensions/exchanges/sim/exchange' . Full error below.

It seems to originate from at module.exports (/app/lib/engine.js:29:20) which has this:

  if(_.isUndefined(s.exchange)){
    if (so.mode !== 'live') {
      s.exchange = require(path.resolve(__dirname, '../extensions/exchanges/sim/exchange'))(conf, s)
    }

Regardless of docker volume exports working or not, isn't this directory not present in the default docker image, therefore why would I get this error?
-------------------------------

Error: Cannot find module '/app/extensions/exchanges/sim/exchange'
at Function.Module._resolveFilename (module.js:548:15)
at Function.Module._load (module.js:475:25)
 at Module.require (module.js:597:17)
at require (internal/module.js:11:18)
at module.exports (/app/lib/engine.js:29:20)
at Command.<anonymous> (/app/commands/trade.js:102:20)
 at Command.listener (/app/node_modules/commander/index.js:315:8)
at emitTwo (events.js:126:13)
at Command.emit (events.js:214:7)
at Command.parseArgs (/app/node_modules/commander/index.js:654:12)

**Comment by DooDiddle** [comment]
If for some reason /app/extensions is not included in the default image, can it be included so I don't get this error?

**Comment by DooDiddle** [comment]
Hello @DeviaVir I think you maintain the docker image deviavir/zenbot
Can you tell me if inside this image is a copy of the folder /app/extensions/exchanges/sim/exchange . I cannot see what's in there since I can't get it to startup

**Comment by DeviaVir** [comment]
```
$ docker run -it --entrypoint=/bin/sh --rm deviavir/zenbot
/app # ls -al /app/extensions/exchanges/sim/
total 12
drwxr-xr-x    1 root     root            22 Oct 24  2018 .
drwxr-xr-x    1 root     root           186 Oct 24  2018 ..
-rw-r--r--    1 root     root          8866 Oct 24  2018 exchange.js
```

**Comment by DooDiddle** [comment]
@DeviaVir Thank you.

I have narrowed the problem down to following:  Inside docker-compose-windows.yml, the volume mounts on windows aren't working. In the case of mounting /extensions folder, I believe it overrides the existing /app/extensions in the image and replaces it with a blank folder. In the case of mapping ./config.js, that simply doesn't work. If I remove the volumes line from the docker-compose-windows, then I can at least start the containers (it finds extensions, but falls back to default config, and of course the default config is missing api keys, etc. so it doesn't do anything useful)

    volumes:
      - ./conf.js:/app/conf.js
      - ./extensions:/app/extensions

How do you fix this? Why do you need to map ./extensions into the docker image if the image already has it, it doesn't look like that's something the user would change. The only thing that's really needed is the config file, then what else can you do to get it in there?

I am using Windows 10, with Docker running in Oracle VirtualBox.

Thank you
