### ISSUE TITLE
Just a sanity check the default branch is not Master

### ISSUE THREAD

**Issue by gilMotta1** [carlos8f/zenbot#1910]
Hey Guys,

I don't know if this on purpose but the default branch is "Unstable" if you type Git Clone and if you don't specify the branch this is what you get.

I am used to the default branch always being "Master"

Just to give you the head up.

Thanks,
Gil

**Comment by DeviaVir** [comment]
Hi,

This is on purpose. This project sees a lot of development from various contributors, `unstable` is the default to indicate some code changes land untested. `master` should be the branch that always has the last tested version.

Hope that clears it up.
