### ISSUE TITLE
Purchase Amount instead of Percent

### ISSUE THREAD

**Issue by chriscrutt** [carlos8f/zenbot#1920]
There are currently two variables - `buy_pct` and `sell_pct` - that can help me limit the amount bought or sold per trade. I was looking for a way to buy or sell specific amounts of currency. For example, when something happens it will purchase $50 in BTC instead of purchasing BTC with say 5% of my balance.

I'm testing on OSX and Ubuntu 16 atm, using Zenbot 4.1.0

Doesn't have to be a perfect solution - I'm looking for a workaround if need be. Maybe if I can somehow make Zenbot think $50 is 5% of my balance? So it uses $50 for every trade.

**Comment by mmdiego** [comment]
If you are writing a strategy, you can do something like:
`s.options.buy_pct = ( amount_in_usd * 100 / s.balance.deposit)`
I´m using that workaround to buy specific amounts in usd.

**Comment by chriscrutt** [comment]
It works beautifully, thank you. Do you think this will this be a feature created in the future?
