### ISSUE TITLE
Bittrex trade error (don't selling/buying)

### ISSUE THREAD

**Issue by cpoho** [carlos8f/zenbot#1970]
API Error
{"success":false,"message":"RATE_PRECISION_NOT_ALLOWED","result":null}
RATE_PRECISION_NOT_ALLOWED

{ Error: order not found in cache
    at Object.getOrder (/home/cpoho/zenbot/extensions/exchanges/bittrex/exchange.js:370:29)
    at checkOrder (/home/cpoho/zenbot/lib/engine.js:831:16)
    at Timeout._onTimeout (/home/cpoho/zenbot/lib/engine.js:309:31)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5) desc: 'could not execute sell: error placing order' }

**Comment by cpoho** [comment]
I'm using default config and these settings:
./zenbot.sh trade --trend_ema 22 -period 3m --max_slippage_pct 0.2 --poll_trades 5000 --order_poll_time 3000 --order_adjust_time 3000 --oversold_rsi_periods=1000 --oversold_r si=1000 --rsi_periods=1100 --neutral_rate=0.017 --max_sell_loss_pct=0.001 --max_buy_loss_pct=5 --buy_pct=100 --sell_pct=100 --selector bittrex.eth-usd --markup_sell_pct 0.001 --markdown_buy_pct 0.001 --reset-profit

**Comment by Astrali** [comment]
can't test right now - could you try following steps:
edit the file: 

> /extensions/exchanges/bittrex/products.json

and in this block here - change the increment to 0.001
```
{
    "asset": "ETH",
    "currency": "USD",
    "min_size": "0.01338091",
    "max_size": "1000000",
    "increment": "0.00000001",
    "label": "USD/ETH"
  },
```

Bittrex only shows 0.001 trades - so i guess 8 increments is probably not accepted

**Comment by cpoho** [comment]
@Astrali thank you! It works well!
