### ISSUE TITLE
Crypto.com exchange support

### ISSUE THREAD

**Issue by jarylc** [carlos8f/zenbot#1999]
Their documentation is here: https://crypto.com/exchange-doc

If I have free time I'll do it and throw a pull request.

**Comment by Seb33300** [comment]
Hello @jarylc, any chance you will work on it in the future?
It looks like no existing bot on the market supports crypto.com

**Comment by jarylc** [comment]
Hey @Seb33300, unfortunately this may be too big of a project for me to start now as I have a day job. Even if I do it'll take awhile.

For now, I don't have plans to take this up. Hopefully someone with more time that can invest into this would pick it up soon.
