### ISSUE TITLE
does not take option arguments anymore...

### ISSUE THREAD

**Issue by e-pangolin** [carlos8f/zenbot#2152]
i tried to remove and reinstall Zenbot from Git, and different versions of NodeJs,
also tried with conf.js from older working zenbot on another VM,

but i still have this new strange problem (while working perfectly if i dont use options):
```

zen@zolw:~/zenbot$ ./zenbot.sh trade --strategy macd --period 2m
internal/modules/cjs/loader.js:979
  throw err;
  ^

Error: Cannot find module '/home/zen/zenbot/extensions/exchanges/--period/exchange'
```
[...]
```

zen@zolw:~/zenbot$ ./zenbot.sh trade --strategy kc --kc_multiplier 2
internal/modules/cjs/loader.js:979
  throw err;
  ^

Error: Cannot find module '/home/zen/zenbot/extensions/exchanges/--kc_multiplier/exchange'
```

```
zen@zolw:~/zenbot$ ./zenbot.sh trade --period 30m binance.ETH-USDT
internal/modules/cjs/loader.js:979
  throw err;
  ^

Error: Cannot find module '/home/zen/zenbot/extensions/exchanges/--period/exchange'
```

etc...
Thanx for help!

**Comment by e-pangolin** [comment]
but "./zenbot.sh trade --strategy macd" works fine

**Comment by DeviaVir** [comment]
That's an odd issue. What operating system are you on? And what terminal do you use?

**Comment by e-pangolin** [comment]
Zenbot runs in a Debian Buster VM, i use Xterm or Mate Terminal (Debian Testing) as terminal.

**Comment by e-pangolin** [comment]
it was working for months, don't know if it broke after dist-upgrade or zenbot update

**Comment by e-pangolin** [comment]
On my Debian Testing laptop i have a few older zenbot version that works, just tested updating zenbot, it also breaks it!

sorry i'm new to git, i backuped directory of older working version but don't know how to see wich exact version it is

**Comment by e-pangolin** [comment]
Ok sorry i think my only working version is quite old, doesn't gives many information:
`
$ git log |head -n 3
commit 4a14757f9b8d76800193be678880a1f220804f2a
Author: Travis CI <travis@travis-ci.org>
Date:   Sat Dec 28 16:43:48 2019 +0000
`
