### ISSUE TITLE
Bitfinex not updating time, not returning balance

### ISSUE THREAD

**Issue by thiagofonsecabarros** [carlos8f/zenbot#2161]
### System information
- **Have I written custom code (as opposed to using zenbot vanilla)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **Zenbot version** (commit ref, or version): latest
- **Zenbot branch**:
- **NodeJS version**: 8.3.0
- **Exact command to reproduce (include everything)**: ./zenbot.sh trade --paper 
- **Did I make any changes to conf-sample.js?**: Added Bitfinex API key and secret, Telegram token, c.selector = 'bitfinex.BTC-USD'

### Describe the problem
I'm trying to run 'trade' for bitfinex, but the same time, pricing and everything is returning static, not updating the dates, times and values. My wallet balance is not being showed, too.

### Source code / Error logs

![screen](https://user-images.githubusercontent.com/20527973/82154619-1589c980-983d-11ea-9377-935f482aa9f7.png)

**Comment by fculpo** [comment]
related to #2223
