### ISSUE TITLE
Couldn't find 'geneticalgorithm'

### ISSUE THREAD

**Issue by ssz360** [carlos8f/zenbot#2250]
When I wanted to install zenbot I was facing into the errors:

> installing genetic_backtester components
> npm ERR! Error while executing:
> npm ERR! C:\Program Files\Git\cmd\git.EXE ls-remote -h -t https://github.com/cmroche/geneticalgorithm.git
> npm ERR!
> npm ERR! remote: Repository not found.
> npm ERR! fatal: repository 'https://github.com/cmroche/geneticalgorithm.git/' not found
> npm ERR!
> npm ERR! exited with error code: 128

After searching I found out that the 'https://github.com/cmroche/geneticalgorithm.git' was removed and originally it was forked from 'https://github.com/panchishin/geneticalgorithm.git' and I could able to install zenbot after replacing it in './scripts/genetic_backtester/package.json'

**Comment by brianunlam** [comment]
I've created a PR to address this issue: #2265
