### ISSUE TITLE
Negative Trading, but all wins?

### ISSUE THREAD

**Issue by dlasher** [carlos8f/zenbot#2264]
System information
- Have I written custom code (as opposed to using zenbot vanilla): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Zenbot version (commit ref, or version): 4.10 (downloaded May 27, 2018)
- Exact command to reproduce (include everything): Any options
- Did I make any changes to conf-sample.js?: No

Trying to understand, get more data, etc. Took a successfully SIM'd strategy, that was averaging 5% wins over a 24H period, and told it to trade live, same exact settings. Very quickly ate itself. :(

last balance: 0.12702085 (-9.59%)
buy hold: 0.14120065 (0.51%)
vs. buy hold: -10.05%
45 trades over 1 days (avg 45.00 trades/day)
win/loss: 25/0
error rate: 0.00%

Every trade that I was able to see on the console was a win, IE buy at 0.194, sell at 0.197, etc. Grabbing the HTML output, shows a graph of clear correct trading, buying low, selling high. The fee is 0.1%, and each trade was a higher percentage of win.

How can you have 25 wins, and lose almost 10%?

https://imgur.com/a/uf4AVoz
https://i.imgur.com/WRGc6EV.png

Invoked as: ./zenbot.sh trade binance.TRX-BTC --avg_slippage_pct=0.045 --buy_stop_pct=29 --markdown_buy_pct=0.25 --markup_sell_pct=0.25 --max_buy_loss_pct=100 --max_sell_loss_pct=100 --max_slippage_pct=5  --order_poll_time=5000 --order_type=taker --period=XX --period_length=XX --profit_stop_enable_pct=6 --profit_stop_pct=15 --quarentine_time=1 --rsi_periods=XX --sell_stop_pct=25 --strategy=wavetrend --symmetrical=false --wavetrend_average_length=XX --wavetrend_channel_length=XX --wavetrend_overbought_1=XX --wavetrend_overbought_2=XX --wavetrend_oversold_1=XX --wavetrend_oversold_2=XX --wavetrend_trends=true --buy_pct=99 --sell_pct=99

**Comment by dlasher** [comment]
So looking at the logs from Binance, it very faithfully bought high and sold low. How in the world does it call that a win?

https://i.imgur.com/dxzUpDR.png

- sim/backtest shows buys/sells at the right places/times, shows a profit.
- post-trading Graph shows buy low sell high
- live console shows buy low sell high
- API action seems to have been buy high, sell low



API bug?

**Comment by dlasher** [comment]
Spending the $$ to test this.. it's just wrong.

buy order completed at 2020-07-09 23:35:18:

63440.32467532 TRX at 0.00000198 BTC
total 0.125611 BTC
0.0000% slippage (orig. price 0.00000198 BTC)
execution: a few seconds

**Looking on Binance, that was a BUY at 0.00000200, not 198.**

Followed by:
2020-07-09 23:37:13 - sell order placed at 0.00000201 BTC

sell order completed at 2020-07-09 23:37:18:

62749.48852706 TRX at 0.00000201 BTC
total 0.126126 BTC
0.0000% slippage (orig. price 0.00000201 BTC)
execution: a few seconds

**Looking on Binance, that was a SELL at 0.00000199, not 201.**

sell order completed at 2020-07-09 23:41:19:

627.97852706 TRX at 0.00000201 BTC
total 0.00126223 BTC
0.0000% slippage (orig. price 0.00000201 BTC)
execution: a few seconds

**Looking on Binance, that was a SELL at 0.00000199, not 201.**

**Comment by dlasher** [comment]
Yeah, something is broken.. Either that or the definition of the word "win" isn't what I think it is:

last balance: 1127.30853769 (-2.26%)
buy hold: 1159.65466062 (0.55%)
vs. buy hold: -2.79%
36 trades over 6 days (avg 6.00 trades/day)
win/loss: 17/2
error rate: 10.52%

**Comment by R4nd0** [comment]
NOT A BUG

TRX ist trading at 0.00000190 in the last candle, zenbot wants to sell now and places a sell order @ 0.00000190
The order book is full of sell orders at 0.00000190 that don't get filled 
The order book is full of buy orders at 0.00000189 that don't get filled 
So zenbot corrects order to 0.00000189 trying to get its order filled. 
Your slippage is 0.5%

TRX ist trading at 0.00000189 now in the last candle, zenbot wants to buy now and places a buy order @ 0.00000189
The order book is full of sell orders at 0.00000190 that don't get filled 
The order book is full of buy orders at 0.00000189 that don't get filled 
So zenbot corrects order to 0.00000190 trying to get its order filled. 
Your slippage is 0.5%

The asset should be traded in USDT. Finer trades are possible here by a factor of 10 as it trades at 0.01738 and the order book moves more frequent. Most likely, you will then have a slippage of 0.05% and lose less.

**Comment by dlasher** [comment]
`So zenbot corrects order to 0.00000189 trying to get its order filled.
Your slippage is 0.5%`

Absolutely is a bug. Slippage is a known, console output, AND Zenbot reporting are indicating a win when it's a loss.

```
Followed by:
2020-07-09 23:37:13 - sell order placed at 0.00000201 BTC

sell order completed at 2020-07-09 23:37:18:

62749.48852706 TRX at 0.00000201 BTC
total 0.126126 BTC
0.0000% slippage (orig. price 0.00000201 BTC)
execution: a few seconds
```

Zenbot doesn't indicate slippage occured, instead it reports  success at the placed order price.

That's a bug.

**Comment by olexiyb** [comment]
This may be related to proposed fix https://github.com/DeviaVir/zenbot/pull/1773
