### ISSUE TITLE
Backfill Error

### ISSUE THREAD

**Issue by Orango1** [carlos8f/zenbot#2285]
Hi all, i got this problem since 2018 version. Please read below and try to fix the issue. 
Thank you

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **Zenbot version** (commit ref, or version): Last version
- **Zenbot branch**: unstable

**### Describe the problem
When i try a BTC-USD pair backfill on bitfinex i got an "duplicate results" and then the backfill process kill itself. It happens also with other pair combo on bitfinex backfill**
It should simply bypass the duplicate block and continue the backfill

### Source code / Error logs
![Error_Backfill](https://user-images.githubusercontent.com/68685281/88266982-723bb180-ccd0-11ea-93cd-8ae6870726f4.jpg)

**Comment by leozzo** [comment]
Hi have the same issue, cant' backfill some pair on bitfinex. It happens since 2018 

Is anybody able to fix this huge problem?

**Comment by fculpo** [comment]
From what I can see, invalid parameters are passed to the backfill.

Please share the complete command line you are using.

**Comment by leozzo** [comment]
it is not a command line problem cause it works correctly for some months of backfill then suddendly it stops and exit on a specified record number. It is so for btc-usd, for eth-usd and other pair. Works correctly with ltc-usd and eos-usd

**Comment by fculpo** [comment]
Im personnally using zenbot on bitfinex btcusd and ethusd, no issue, so yes
must be parameters

**Comment by leozzo** [comment]
you successfully backfilled all data since 2017 to today? 

Btw there is no valid reason why zenbot have to stop and kill itself when it find a duplicated block. This issue shoud be fixed

**Comment by leozzo** [comment]
Any fix for this issue?
