### ISSUE TITLE
Zenbot and coinbase /kraken

### ISSUE THREAD

**Issue by raven4d** [carlos8f/zenbot#2499]
H

i would like to report an issue which blocks me using zenbot, thanks for the efforts!

### System information
- **Have I written custom code (as opposed to using zenbot vanilla)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux debian 4.9.0-14-amd64 #1 SMP Debian 4.9.240-2 (2020-10-30) x86_64 GNU/Linux

- **Zenbot version** 4.1.0
- **Zenbot branch**:
- **NodeJS version**:8 - 12 - 15
- **Python version (when using a python script)**:  Python 2.7.13
- **Exact command to reproduce (include everything)**: zenbot balance for coinbase or zenbot trade for kraken ( strategy set in the config.js) 

- **Did I make any changes to conf-sample.js?**:no, i just copied it to conf.js and added the API keys for coinbase / Kraken 

### Describe the problem
zenbot cant handel my coinbase account, with the error
GDAX API is down! unable to call getBalance, retrying in 10s
Error: HTTP 401 Error: request timestamp expired

zenbot can handel Kraken API, but its givving every so often the error 
Kraken API warning - unable to call getBalance (Error: API:Invalid nonce), retrying in 0.15s

am not a developer, so i presumed the issue is because the node.js is old (version 8 as the isntall document suggest) so i tried version 12 and 15 as well, with the same results .

any help would be appreciated!
regards

**Comment by yellowgh0st** [comment]
You're trying to connect to GDAX.

**Comment by fcjreed** [comment]
Request timestamp expired typically happens if your system time is out of sync. Try enabling ntp syncing.
