### ISSUE TITLE
Docker build currently not working

### ISSUE THREAD

**Issue by XL-Reaper** [carlos8f/zenbot#2535]
Currently the docker-compose build command terminates because of a wrong / missing dependecy:

husky > Setting up git hooks
Husky requires Git >=2.13.0. Got v2.11.0.
husky > Failed to install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! husky@4.3.1 install: `node husky install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the husky@4.3.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by jorisw** [comment]
This is not related to the skipped optional dependency, but rather, your git client version.

**Comment by XL-Reaper** [comment]
It's not "my" client that isn't working there, but the one being used in the docker build image.

**Comment by jorisw** [comment]
The image was added in #2216 , perhaps @fculpo can take a look

**Comment by pat412** [comment]
can confirm: checkout and run via docker not working at the moment, same issue here

**Comment by josefalanga** [comment]
looks like the last time it built was november 10 on commit `c9b43a420922bbf4c8deaf05f1e220a9e34416e8`

it's related to #2489

**Comment by XL-Reaper** [comment]
Pull request merged

**Comment by jorisw** [comment]
Fixed in #2582
