### ISSUE TITLE
"getBalance error: Permission denied" on Poloniex Live Trading

### ISSUE THREAD

**Issue by samdude19** [carlos8f/zenbot#2619]
Hi Team,

I am getting the below error message while trying to use the bot for live (not the simulation) trading on Poloniex. Is it due to exchange settings that Poloniex doesn't allow support market trades via API?
.
	"getBalance error:
	{ error: 'Permission denied.' }"

Zenbot v 4.04. I have also provided the API details in the conf.js file.

![image](https://user-images.githubusercontent.com/77722044/105158385-eea23680-5b33-11eb-92df-4425a935b1e2.png)

**Comment by DeviaVir** [comment]
Make sure the API key has permissions to get your balance, too.
