### ISSUE TITLE
zenbot not start

### ISSUE THREAD

**Issue by hbheiner** [carlos8f/zenbot#2626]
PS C:\zenbot> docker-compose --file=docker-compose-windows.yml up --remove-orphans
Removing zenbot_server_1
Starting zenbot_mongodb-data_1 ... done
Starting zenbot_mongodb_1      ... done
Recreating fe1bef2d1e57_zenbot_server_1 ... error

ERROR: for fe1bef2d1e57_zenbot_server_1  Cannot start service server: Cannot link to a non running container: /zenbot_mongodb_1 AS /zenbot_server_1/mongodb

ERROR: for server  Cannot start service server: Cannot link to a non running container: /zenbot_mongodb_1 AS /zenbot_server_1/mongodb
ERROR: Encountered errors while bringing up the project.
PS C:\zenbot>

i have installed node v14.15.4 and mongo db4.4.3 on windows 10

**Comment by romainvaltier** [comment]
Maybe following option is missing in docker-compose-windows.yml:
`    depends_on:
      - mongodb`
