### ISSUE TITLE
Web output issue - no charts/graphics

### ISSUE THREAD

**Issue by Maddcow** [carlos8f/zenbot#2631]
### System information
- **Have I written custom code (as opposed to using zenbot vanilla)**: no - using installed codes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10 with Docker v20.10.2
- **Zenbot version** (commit ref, or version):  on commit 3,637
- **Zenbot branch**: DeviaVir
- **NodeJS version**: v10.23.2
- **Python version (when using a python script)**:
- **Exact command to reproduce (include everything)**: docker-compose up
- **Did I make any changes to conf-sample.js?**: Updated ccxt API keys

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in Zenbot or a feature request.
    I am using Docker and can verify from the console that Zenbot is running (in --paper mode). Opening the local website shows only dashboard text output - there are no charts or graphics on the page. I have verified on Edge, IE, and Chrome with the same issue on each. Any suggestions?

I would submit a screen shot put its just a large blank space with just the dashboard text.

**Comment by dereckmartin** [comment]
if you are using docker, i had to use my system ip like 192.168.0.1:17365 in the browser versus localhost:17365 or 127.0.0.1:17365.  Some of the javascript resources will not load using localhost.  You can find this out by using devtools console in firefox or chrome.

**Comment by Maddcow** [comment]
That brings up the same thing (thanks tho). I am starting Zenbot with cmd and see output but it is not excepting any commands - ie l = list available commands. I think this is why the website is not showing anything because I am not able to dump from the CLI. 

Do I need to start the docker with -d and run trade --paper from within the docker cli (just to a different port)? Or is there a way to get the cmd window to take my inputs? Any suggestions would be great.

**Comment by Maddcow** [comment]
After updating docker-compose.yml file to the deviavir/zenbot:unstable image and rebuilding the Docker - everything is working.
