### ISSUE TITLE
It seems WexNZ exchange has been closed since 2018

### ISSUE THREAD

**Issue by tommyyama2020** [carlos8f/zenbot#2647]
### System information
- **Have I written custom code (as opposed to using zenbot vanilla)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac OS ver 11.2.1
- **Zenbot version** (commit ref, or version):
- **Zenbot branch**: unstable
- **NodeJS version**: 15.8.0
- **Python version (when using a python script)**:
- **Exact command to reproduce (include everything)**: NA
- **Did I make any changes to conf-sample.js?**:

### Describe the problem
It seems that they has closed their business in 2018. 
please rm its exchange folder and update other new ones open now.  In addition, Appreciated if you give me a permission to git push, pull so that i am going to be able to request a pull to you (only if possible).  

### Source code / Error logs
Wexnz folder in /Users/tomomi/Public/zenbot/extensions/exchanges

**Comment by DeviaVir** [comment]
Fixed in https://github.com/DeviaVir/zenbot/pull/2648
