### ISSUE TITLE
binanceus update-products.sh not triggering

### ISSUE THREAD

**Issue by grainz** [carlos8f/zenbot#2650]
update-products.sh needs to be marked as an executable for binanceus to regularly update tokens.

**Comment by grainz** [comment]
Can we link this to my pull request so it can get closed out?
https://github.com/DeviaVir/zenbot/pull/2669

**Comment by DeviaVir** [comment]
You just did so by linking it here, good to close this one?

**Comment by grainz** [comment]
i thought there was a way to link it on the right of the ticket but either way, we can close this as resolved.
