### ISSUE TITLE
Docker Traefik - ERROR: Invalid interpolation format for "labels" option in service "zenbotserver": "traefik.frontend.rule=Host:$(TRAEFIK_HOST_ZEN)"

### ISSUE THREAD

**Issue by sebastienhouzet** [carlos8f/zenbot#2663]
### System information
- **Have I written custom code (as opposed to using zenbot vanilla)**:

zenbot vanilla

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:

Mac OS + Docker

- **Zenbot version** (commit ref, or version):

Latest

- **Zenbot branch**:

unstable

- **NodeJS version**:

10

- **Exact command to reproduce (include everything)**:

Before, i have copy .env-sample to .env

$ docker-compose -f docker-compose-traefik.yml up

- **Did I make any changes to conf-sample.js?**:

Yes

### Describe the problem
If you want to use docker-compose version with traefik

### Source code / Error logs
$ docker-compose -f docker-compose-traefik.yml up
ERROR: Invalid interpolation format for "labels" option in service "zenbotserver": "traefik.frontend.rule=Host:$(TRAEFIK_HOST_ZEN)"

**Comment by chris-aeviator** [comment]
I mostly have this issue when having a string (e.g. from htpasswd) that has a `$` in there. I get around this by preprending every `$` with another `$` , but this might break your usecase. You can try just replacing your ENV variable TRAEFIK_HOST_ZEN with the actual value
