### ISSUE TITLE
Issue with docker: Error: listen EADDRINUSE: address already in use :::17365

### ISSUE THREAD

**Issue by michK** [carlos8f/zenbot#2752]
Hi,

I'm having an issue starting up a bot with a docker build of zenbot.

I'm on a Ubuntu 18.04 system.

I have most of the setup done, and start up the server with

`docker-compose up`

which seems to exacute fine, although it automatically goes into paper trading mode; is that normal?

I have my `conf.js` set up and it seems to work because I was able to submit an order that exacuted on pro.coinbase with:

`docker-compose exec server zenbot buy gdax.BTC-USD`

However, when I try to start a bot with

`docker-compose exec server zenbot trade`

I get the error

`Error: listen EADDRINUSE: address already in use :::17365`.

I think the issue is that `docker-compose up` outputs to the same port as the bot, but when I try to run the
bot without `docker-compose up`, I get the error

`ERROR: No container found for server_1`

Any ideas?

**Comment by michK** [comment]
I have found a workaround that's not very elegent:

Start server with `docker-compose up`

Open `conf.js` and change `c.output.api.port = process.env.ZENBOT_API_PORT` to different port

And then start bot with `docker-compose exec server zenbot trade`

Seems to work, but not very elegant.

**Comment by jeff47** [comment]
Pretty sure it's because the default docker already starts zenbot running within the container, so it's already running and listening on port 17365.
